


casper.notebook_test(function() {
    "use strict";

    casper.test.info("Testing uploading notebook to DSpace");

    this.viewport(1024, 768);

    //wait for notebook to load
    this.waitFor(this.kernel_running);
    this.waitFor(function() {
        return this.evaluate(function () {
            return Jupyter && Jupyter.notebook && true;
        });
    });

    var nbname = "Untitled.ipynb";

    this.thenEvaluate(function (nbname) {
        require(['base/js/events'], function (events) {
            Jupyter.notebook.set_notebook_name(nbname);
            var md = Jupyter.notebook.metadata;
            md.reportmetadata = {
                "abstract": "A test item generated by upload_to_dspace.js If you can see this then the delete part of the test isn't working",
                "referencedBy": [
                  "Test"
                ],
                "tags": [
                  "Test"
                ],
                "language": "en",
                "authors": [
                  [
                    "McTestface",
                    "Testy"
                  ]
                ],
                "date": "2016-11-14",
                "title": "TO BE DELETED",
                "repository": "edata/8",
            };
            Jupyter._save_success = Jupyter._save_failed = false;
            events.on('notebook_saved.Notebook', function () {
                Jupyter._save_success = true;
            });
            events.on('notebook_save_failed.Notebook',
                function (event, error) {
                    Jupyter._save_failed = "save failed with " + error;
            });
            Jupyter.notebook.save_notebook();
        });
    }, {nbname:nbname});
    
    this.waitFor(function () {
        return this.evaluate(function(){
            return Jupyter._save_failed || Jupyter._save_success;
        });
    });

    this.then(function(){
        var success_failure = this.evaluate(function(){
            return [Jupyter._save_success, Jupyter._save_failed];
        });
        this.test.assertEquals(success_failure[1], false, "Save did not fail");
        this.test.assertEquals(success_failure[0], true, "Save OK");
    });

    //Click on menu item
    var selector = '#sword_new_item > a';
    this.waitForSelector(selector);
    this.thenClick(selector);

    var alert = '.alert';
    this.waitForSelector(alert);
    this.then(function() {
        var alert_element = this.getElementAttribute(alert,'class');
        this.test.assertEquals(alert_element,"alert alert-dismissible fade in alert-success","Success alert seen");
    });
    
    var id = "";

    this.then(function() {
        this.evaluate(function() {
            var id_url = $('.alert-success').attr("item-id");
            var request_url = require("base/js/utils").url_path_join.apply(null,[Jupyter.notebook.base_url, '/dspacetest']);
            var settings = {
                processData : false,
                cache : false,
                type : "GET",
                dataType : "json",
            };
            var request = require("base/js/utils").promising_ajax(request_url + '?' + $.param({"ID":id_url}), settings);
            request.then(function(result) {
                $(document.body).append($('<div/>').attr('id','test-item-id').attr('item-id',result.id));
            });
        });
    });

    this.waitForSelector("#test-item-id");


    this.then(function() {
        id = this.getElementAttribute('#test-item-id',"item-id");
        this.test.assertNotEquals(id,"","The item exists in DSpace with the ID " + id);
    });

    this.then(function() {
        this.evaluate(function(id) {
            var request_url = require("base/js/utils").url_path_join.apply(null,[Jupyter.notebook.base_url, '/dspacetest']);
                var settings = {
                    processData : false,
                    type : "DELETE",
                    dataType : "json",
                };
                var request = require("base/js/utils").promising_ajax(request_url + '?' + $.param({"ID":id}), settings);

                request.then(function(result) {
                $(document.body).append($('<div/>').attr('id','test-delete-status').attr('status-code',result));
            });
        }, {id:id});
    });

    this.waitForSelector("#test-delete-status");

    this.then(function() {
        var delete_status_code = this.getElementAttribute('#test-delete-status',"status-code");
        this.test.assertEquals(delete_status_code,"404","Item not found in DSpace so successfully deleted");
    });

});
